[tools]
"npm:bash-language-server" = "5.6.0"
"npm:typescript-language-server" = "5.1.3"
"npm:svelte-language-server" = "0.17.22"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:prettier" = "3.7.3"
"npm:eslint" = "9.39.1"

[tools.nodejs]
version = "latest"
