[tools]
bat = "latest"
btop = "latest"
direnv = "latest"
fzf = "latest"
gitleaks = "latest"
hyperfine = "latest"
just = "latest"
mprocs = "latest"
ripgrep = "latest"
tmux = "latest"
zoxide = "latest"

bun = "latest"
deno = "latest"
opencode = "latest"
"github:seaofvoices/darklua" = "latest"

[settings]
cargo = { binstall = true }
experimental = true
jobs = 4                    # internet & cpu resources ain't cheap friend
npm = { bun = true }
paranoid = false
verbose = false
