[tools]
# cli
bat = "latest"
btop = "latest"
direnv = "latest"
gitleaks = "latest"
hyperfine = "latest"
just = "latest"
lazygit = "latest"
mprocs = "latest"
ripgrep = "latest"
tmux = "latest"
uv = "latest"
zoxide = "latest"


# editor
ruff = "latest"
shfmt = "3.12.0"
stylua = "latest"
tinymist = "latest"
typst = "latest"
typstyle = "latest"
fzf = "latest"
opencode = "latest"
"cargo:emmylua_check" = "0.17.0"
"cargo:emmylua_doc_cli" = "0.17.0"
"cargo:emmylua_ls" = "0.17.0"


#etc
"github:Inlyne-Project/inlyne" = "0.5.0"
"github:JohnnyMorganz/luau-lsp" = "1.56.2"
"github:adalinesimonian/gdvm" = "0.9.0"
"github:lumen-oss/lux" = "0.20.1"
"github:lune-org/lune" = "0.10.4"


# rust
rust = { version = "latest", components = "cargo,clippy,rust-src,rustc,rust-std,rustfmt,rust-analyzer" }
cargo-binstall = "latest"
taplo = "latest"
"cargo:trunk" = "latest"


# nodejs
node = "latest"
"npm:bash-language-server" = "5.6.0"
"npm:typescript-language-server" = "5.1.3"
"npm:svelte-language-server" = "0.17.22"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:prettier" = "3.7.3"
"npm:eslint" = "9.39.1"

deno = "latest"


# dotnet
dotnet = "latest"
"github:SofusA/csharp-language-server" = { version = "5.3.0-2.25557.9", bin = "roslyn-ls" }


# java
java = "latest"
gradle = "latest"
zig = "0.15.2"
zls = "0.15.0"

[tools."http:jdtls"]
checksum = "sha256:1a291a269bd88b3c4048219122961a52ec80872afbc7a3f34270b2ce77f7a14c"
version = "1.54.0"
url = "https://download.eclipse.org/jdtls/milestones/{{version}}/jdt-language-server-{{version}}-202511261751.tar.gz"

[settings]
experimental = true
